all:
	@javac MyHashTable_.java
	@javac NodeDH.java
	@javac MyHashTableDH.java
	@javac NodeSCBST.java
	@javac MyHashTableSCBST.java
	@javac Student_.java
	@javac Student.java
	@javac Pair.java
	@javac Assignment3.java
	@java Assignment3 72 DH input.txt
	@java Assignment3 32 SCBST input.txt
	@rm *.class
